---
language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"

stages:
  - style check
  - build

stage: build

install: python setup.py install
script: aurblobs

jobs:
  include:
    - stage: style check
      name: "Check for pep8 style"
      python: "3.7"
      install: pip install flake8
      script: flake8 aurblobs/

notifications:
  email: false
