---
language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install flake8

script:
  - flake8 aurblobs/
  - python setup.py install
  - aurblobs

notifications:
  email: false
